name: Test D&D App's build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: [12.x]
    - name: Build Test
      run: |
        npm install
        yarn gulp sass
        npm run build --if-present
        npm audit fix
